name: 'Python cache'
description: 'Cache Python dependencies'
inputs:
  lock_file:
    description: 'Path to the uv.lock file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python + uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          tools/hextech/uv.lock
          ${{ inputs.lock_file }}
