[tool.poetry]
name = "monorepo"
version = "0.1.0"
description = ""
authors = ["Noel Wilson <jwnwilson@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.5"
cookiecutter = "^2.6.0"
pyyaml = "^6.0.2"
boto3 = "^1.35.58"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
