"""Adding Company and FeatureFlag

Revision ID: 189dea131495
Revises: 1637f38542d9
Create Date: 2025-02-02 21:19:24.791338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189dea131495'
down_revision = '1637f38542d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('website')
    )
    op.create_table('feature_flag',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('permission_groups', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('permission_groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permission_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permission_users', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('permission_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('permission_users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    op.add_column('user_groups', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('user_groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'updated_at')
    op.drop_column('user_groups', 'created_at')
    op.drop_column('user_groups', 'id')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'company_id')
    op.drop_column('permission_users', 'updated_at')
    op.drop_column('permission_users', 'created_at')
    op.drop_column('permission_users', 'id')
    op.drop_column('permission_groups', 'updated_at')
    op.drop_column('permission_groups', 'created_at')
    op.drop_column('permission_groups', 'id')
    op.drop_table('feature_flag')
    op.drop_table('company')
    # ### end Alembic commands ###
