"""Add Company Feature flags

Revision ID: f2e5d57ed431
Revises: 75aca05b1f20
Create Date: 2025-02-03 20:55:05.419023

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2e5d57ed431"
down_revision = "75aca05b1f20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("feature_flag", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "feature_flag", "company", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "feature_flag", type_="foreignkey")
    op.drop_column("feature_flag", "company_id")
    # ### end Alembic commands ###
