"""DB migration

Revision ID: 98e865fe838b
Revises: f2e5d57ed431
Create Date: 2025-02-16 10:06:06.367132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e865fe838b'
down_revision = 'f2e5d57ed431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_email_idx', 'user', ['email'], unique=False)
    op.create_index('user_username_idx', 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_username_idx', table_name='user')
    op.drop_index('user_email_idx', table_name='user')
    # ### end Alembic commands ###
