"""Adding permisisons versioning

Revision ID: ef803cb00ba1
Revises: 98e865fe838b
Create Date: 2025-03-01 14:00:39.986503

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef803cb00ba1"
down_revision = "98e865fe838b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_groups_version",
        sa.Column("permission_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("group_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_permission_groups_version_end_transaction_id"),
        "permission_groups_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_groups_version_operation_type"),
        "permission_groups_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_groups_version_transaction_id"),
        "permission_groups_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "permission_users_version",
        sa.Column("permission_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_permission_users_version_end_transaction_id"),
        "permission_users_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_users_version_operation_type"),
        "permission_users_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_users_version_transaction_id"),
        "permission_users_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "permission_version",
        sa.Column("name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_permission_version_end_transaction_id"),
        "permission_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_version_operation_type"),
        "permission_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_version_transaction_id"),
        "permission_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_index(
        op.f("ix_permission_version_transaction_id"), table_name="permission_version"
    )
    op.drop_index(
        op.f("ix_permission_version_operation_type"), table_name="permission_version"
    )
    op.drop_index(
        op.f("ix_permission_version_end_transaction_id"),
        table_name="permission_version",
    )
    op.drop_table("permission_version")
    op.drop_index(
        op.f("ix_permission_users_version_transaction_id"),
        table_name="permission_users_version",
    )
    op.drop_index(
        op.f("ix_permission_users_version_operation_type"),
        table_name="permission_users_version",
    )
    op.drop_index(
        op.f("ix_permission_users_version_end_transaction_id"),
        table_name="permission_users_version",
    )
    op.drop_table("permission_users_version")
    op.drop_index(
        op.f("ix_permission_groups_version_transaction_id"),
        table_name="permission_groups_version",
    )
    op.drop_index(
        op.f("ix_permission_groups_version_operation_type"),
        table_name="permission_groups_version",
    )
    op.drop_index(
        op.f("ix_permission_groups_version_end_transaction_id"),
        table_name="permission_groups_version",
    )
    op.drop_table("permission_groups_version")
    # ### end Alembic commands ###
