"""DB migration

Revision ID: 509c390208a5
Revises: ef803cb00ba1
Create Date: 2025-03-02 09:05:39.772576

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "509c390208a5"
down_revision = "ef803cb00ba1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_version",
        sa.Column("name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_group_version_end_transaction_id"),
        "group_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_version_operation_type"),
        "group_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_version_transaction_id"),
        "group_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "user_groups_version",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("group_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_user_groups_version_end_transaction_id"),
        "user_groups_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_groups_version_operation_type"),
        "user_groups_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_groups_version_transaction_id"),
        "user_groups_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "user_version",
        sa.Column("username", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("email", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("name", sa.String(), autoincrement=False, nullable=True),
        sa.Column("cognito_id", sa.String(), autoincrement=False, nullable=True),
        sa.Column("verified", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("company_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_user_version_end_transaction_id"),
        "user_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_version_operation_type"),
        "user_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_version_transaction_id"),
        "user_version",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_version_transaction_id"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_operation_type"), table_name="user_version")
    op.drop_index(op.f("ix_user_version_end_transaction_id"), table_name="user_version")
    op.drop_table("user_version")
    op.drop_index(
        op.f("ix_user_groups_version_transaction_id"), table_name="user_groups_version"
    )
    op.drop_index(
        op.f("ix_user_groups_version_operation_type"), table_name="user_groups_version"
    )
    op.drop_index(
        op.f("ix_user_groups_version_end_transaction_id"),
        table_name="user_groups_version",
    )
    op.drop_table("user_groups_version")
    op.drop_index(op.f("ix_group_version_transaction_id"), table_name="group_version")
    op.drop_index(op.f("ix_group_version_operation_type"), table_name="group_version")
    op.drop_index(
        op.f("ix_group_version_end_transaction_id"), table_name="group_version"
    )
    op.drop_table("group_version")
    # ### end Alembic commands ###
