"""Unique permissions

Revision ID: ca33439c6bae
Revises: 509c390208a5
Create Date: 2025-03-02 12:23:06.718565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca33439c6bae'
down_revision = '509c390208a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('permission_name_idx', 'permission', ['name'], unique=False)
    op.create_unique_constraint(None, 'permission', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_index('permission_name_idx', table_name='permission')
    # ### end Alembic commands ###
