"""Adding env table and improving feature flag schema

Revision ID: 270a641c7d8a
Revises: ca33439c6bae
Create Date: 2025-04-13 10:33:55.259181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '270a641c7d8a'
down_revision = 'ca33439c6bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_flag_env',
    sa.Column('feature_flag_id', sa.UUID(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('env', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_flag_id', 'env', name='uq_feature_flag_env')
    )
    op.create_unique_constraint(None, 'feature_flag', ['name'])
    op.drop_constraint('feature_flag_company_id_fkey', 'feature_flag', type_='foreignkey')
    op.drop_column('feature_flag', 'company_id')
    op.drop_column('feature_flag', 'enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flag', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('feature_flag', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('feature_flag_company_id_fkey', 'feature_flag', 'company', ['company_id'], ['id'])
    op.drop_constraint(None, 'feature_flag', type_='unique')
    op.drop_table('feature_flag_env')
    op.drop_table('environment')
    # ### end Alembic commands ###
