"""Adding feature flag env and overrides

Revision ID: a63c7f650c87
Revises: ca33439c6bae
Create Date: 2025-04-12 17:24:53.193768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63c7f650c87'
down_revision = 'ca33439c6bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag_env',
    sa.Column('feature_flag_id', sa.UUID(), nullable=False),
    sa.Column('env', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_flag_override',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('feature_flag_company_id_fkey', 'feature_flag', type_='foreignkey')
    op.drop_column('feature_flag', 'enabled')
    op.drop_column('feature_flag', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flag', sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('feature_flag', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('feature_flag_company_id_fkey', 'feature_flag', 'company', ['company_id'], ['id'])
    op.drop_table('feature_flag_override')
    op.drop_table('feature_flag_env')
    # ### end Alembic commands ###
