"""Nullable feature flag overrides

Revision ID: 25b90ede05f5
Revises: 270a641c7d8a
Create Date: 2025-04-14 17:39:22.946833

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "25b90ede05f5"
down_revision = "270a641c7d8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature_flag_env",
        "overrides",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature_flag_env",
        "overrides",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###
