"""Adding featue flag override FK

Revision ID: b24d3737ea45
Revises: a63c7f650c87
Create Date: 2025-04-12 18:31:14.634999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24d3737ea45'
down_revision = 'a63c7f650c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flag_override', sa.Column('feature_flag_env_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'feature_flag_override', 'feature_flag_env', ['feature_flag_env_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature_flag_override', type_='foreignkey')
    op.drop_column('feature_flag_override', 'feature_flag_env_id')
    # ### end Alembic commands ###
