"""Unique feature flag name constraint

Revision ID: 8f8738563f5b
Revises: 25b90ede05f5
Create Date: 2025-04-14 17:46:45.384782

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f8738563f5b"
down_revision = "25b90ede05f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_feature_flag_name", "feature_flag", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_feature_flag_name", "feature_flag", type_="unique")
    # ### end Alembic commands ###
