[project]
name = "hexrepo_task"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "hexrepo-db",
    "pymongo>=4.10.1",
]

[tool.uv.sources]
hexrepo-db = { path = "../../adaptor/db", editable = true }

[dependency-groups]
dev = [
    "mypy<2.0.0,>=1.13.0",
    "httpx<1.0.0,>=0.27.2",
    "pytest<9.0.0,>=8.3.3",
    "pytest-dotenv<1.0.0,>=0.5.2",
    "pytest-cov<7.0.0,>=6.0.0",
    "pytest-xdist<4.0.0,>=3.6.1",
    "polyfactory<3.0.0,>=2.17.0",
    "ruff>=0.8.4",
]
