# Generated by Django 5.2.5 on 2025-08-09 10:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="passwordreset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
