
[project]
authors = [
    {name = "Noel Wilson", email = "jwnwilson@hotmail.co.uk"},
]
requires-python = "<4.0,>=3.12"
name = "example"
version = "0.1.0"
description = "A short description of the project"
readme = "README.md"
dependencies = [
    "fastapi<1.0.0,>=0.115.3",
    "uvicorn<1.0.0,>=0.32.0",
    "requests<3.0.0,>=2.32.3",
    "python-dotenv<2.0.0,>=1.0.1",
    "pydantic-settings<3.0.0,>=2.6.0",
    "alembic<2.0.0,>=1.13.3",
    "gevent<25.0.0,>=24.10.3",
    "psycopg2-binary<3.0.0,>=2.9.10",
    "boto3<2.0.0,>=1.35.66",
    "monorepo-cloud @ file:///${PROJECT_ROOT}/../../libs/adaptor/cloud",
    "monorepo-db @ file:///${PROJECT_ROOT}/../../libs/adaptor/db",
    "monorepo-api @ file:///${PROJECT_ROOT}/../../libs/interactor/api",
    "boto3-stubs[essential]<2.0.0,>=1.35.86",
]

[dependency-groups]
dev = [
    "pytest<9.0.0,>=8.3.3",
    "mypy<2.0.0,>=1.13.0",
    "black<25.0.0,>=24.10.0",
    "isort<6.0.0,>=5.13.2",
    "httpx<1.0.0,>=0.27.2",
    "pytest-dotenv<1.0.0,>=0.5.2",
    "pytest-cov<7.0.0,>=6.0.0",
    "pytest-xdist<4.0.0,>=3.6.1",
    "polyfactory<3.0.0,>=2.17.0",
]
aws = [
    "mangum<1.0.0,>=0.19.0",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-vv --cov --cov-report xml --cov-report term-missing --cov-fail-under=50"
asyncio_mode = "auto"
testpaths = ["src/tests"]
env_files = ["env/local.env"]
pythonpath = [
  "src"
]

[tool.coverage.run]
concurrency = ["gevent"]
omit = ["src/tests/*"]
source = ["app"]

[tool.mypy]
python_version = "3.12"
strict = true
