# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#
version: '3'
services:
  api:
    container_name: {{cookiecutter.project_slug}}
    platform: "linux/amd64"
    env_file:
      - env/docker.env
    image: "{{cookiecutter.project_slug}}"
    build: 
      context: ../../
      dockerfile: infra/docker/{{cookiecutter.cloud_provider}}.Dockerfile
      args:
          PROJECT: example
    # Run this contain as if it's in the terminal, useful for debugging
    tty: true
    # Mount local files into the container so we can update files inside the container
    volumes:
      - ../../libs:/libs
      - ./src:/code/src
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000
    {% if cookiecutter.use_db == "y" %}
    depends_on:
      - postgres_db
    {% endif %}
    {% if cookiecutter.cloud_provider == "aws" %}
    # Override lambda entry point to revert to default docker behaviour
    entrypoint: ""
    command: "uvicorn app.adapter.into.fastapi.main:app --host 0.0.0.0 --port 80 --reload --debug"
    {% endif %}

{% if cookiecutter.use_db == "y" and cookiecutter.use_db_logic == 'sql' %}
  postgres_db:
    container_name: {{cookiecutter.project_slug}}_db
    restart: unless-stopped
    image: postgres:15
    volumes:
      - ./tools/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - ./tools:/code/tools
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES={{cookiecutter.project_slug}}_db,test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    env_file:
      - env/docker.env
    ports:
      - "0.0.0.0:5432:5432"
    expose:
      - "5432"
{% endif %}
{% if cookiecutter.use_db == "y" and cookiecutter.use_db_logic == 'nosql' %}
  dynamodb-local:
    container_name: monorepo_dynamodb
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "0.0.0.0:8000:8000"
    expose:
      - "8000"
    working_dir: /home/dynamodblocal
    volumes:
     - dynamo_db:/home/dynamodblocal/data
{% endif %}


volumes:
  {% if cookiecutter.use_db == "y" and cookiecutter.use_db_logic == 'sql' %}
  postgres_db:
  {% endif %}
  {% if cookiecutter.use_db == "y" and cookiecutter.use_db_logic == 'nosql' %}
  dynamo_db:
  {% endif %}
