[project]
authors = [
    {name = "{{cookiecutter.full_name}}", email = "{{cookiecutter.email}}"},
]
requires-python = "<4.0,>=3.12"
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.description}}"
readme = "README.md"
dependencies = [
    {% if cookiecutter.use_api == 'y' %}
    "fastapi<1.0.0,>=0.115.3",
    "uvicorn<1.0.0,>=0.32.0",
    "gevent<25.0.0,>=24.10.3",
    {% endif %}
    "requests<3.0.0,>=2.32.3",
    "python-dotenv<2.0.0,>=1.0.1",
    "pydantic-settings<3.0.0,>=2.6.0",
    {% if cookiecutter.use_db == 'y' and cookiecutter.use_db_logic == 'sql' %}
    "alembic<2.0.0,>=1.13.3",
    "psycopg2-binary<3.0.0,>=2.9.10",
    {% elif cookiecutter.use_db == 'y' and cookiecutter.use_db_logic == 'nosql' %}
    "pymongo>=4.10.1",
    {% endif %}
    {% if cookiecutter.use_storage == 'y' %}
    "boto3<2.0.0,>=1.35.66",
    "boto3-stubs[essential]<2.0.0,>=1.35.86",
    "hexrepo-cloud @ file:///${PROJECT_ROOT}/../../libs/adaptor/cloud",
    {% endif %}
    {% if cookiecutter.use_db == 'y' %}
    "hexrepo-db @ file:///${PROJECT_ROOT}/../../libs/adaptor/db",
    {% endif %}
    {% if cookiecutter.use_api == 'y' %}
    "hexrepo-api @ file:///${PROJECT_ROOT}/../../libs/interactor/api",
    {% endif %}
]

[dependency-groups]
aws = [
    "mangum<1.0.0,>=0.19.0",
]
dev = [
    "pytest<9.0.0,>=8.3.3",
    "mypy<2.0.0,>=1.13.0",
    "ruff>=0.8.4",
    "httpx<1.0.0,>=0.27.2",
    "pytest-dotenv<1.0.0,>=0.5.2",
    "pytest-cov<7.0.0,>=6.0.0",
    "pytest-xdist<4.0.0,>=3.6.1",
    "polyfactory<3.0.0,>=2.17.0",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = "-vv --cov --cov-report xml --cov-report term-missing --cov-fail-under=50"
testpaths = ["app/tests"]
env_files = ["env/local.env"]
pythonpath = [
  "src"
]

[tool.coverage.run]
concurrency = ["gevent"]
omit = ["app/tests/*"]
source = ["app"]

[tool.mypy]
python_version = "3.12"
strict = true