# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#
version: '3'
services:
  api:
    container_name: auth
    platform: "linux/amd64"
    env_file:
      - env/docker.env
    image: "auth"
    build: 
      context: ../../
      dockerfile: infra/docker/aws.Dockerfile
      args:
          PROJECT: auth
    # Run this contain as if it's in the terminal, useful for debugging
    tty: true
    # Mount local files into the container so we can update files inside the container
    volumes:
      - ../../libs:/libs
      - ./src:/code/src
    expose:
      - "8000"
    ports:
      - 0.0.0.0:8000:8000
    depends_on:
      - db
    # Override lambda entry point to revert to default docker behaviour
    entrypoint: ""
    command: "uvicorn app.adaptor.into.fastapi.main:app --host 0.0.0.0 --port 80 --reload --debug"

  localstack:
    container_name: "auth-localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=1
    volumes:
      - localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  localstack:
