ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-staging"
  hosts:
    - host: test.jwnwilson.co.uk
      paths: ["/"]
  tls:
   - secretName: expressjs-tls
     hosts:
       - test.jwnwilson.co.uk