[tool.poetry]
name = "hextech"
version = "0.1.0"
description = ""
authors = ["Noel Wilson <jwnwilson@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.15.1"
cookiecutter = "^2.6.0"
pyyaml = "^6.0.2"
boto3 = "^1.35.58"
pydantic-settings = "^2.6.1"
monorepo-cloud = {path = "../../libs/src/adaptor/cloud", develop = true}

[tool.poetry.scripts]
hextech = "hextech.interactor.cli:app"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cookies = "^0.7.0"
mypy = "^1.13.0"
black = "^24.10.0"
isort = "^5.13.2"
httpx = "^0.27.2"
pytest-dotenv = "^0.5.2"
pytest-cov = "^6.0.0"
pytest-xdist = "^3.6.1"
boto3-stubs = {extras = ["essential"], version = "^1.35.86"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
