[project]
authors = [
    {name = "Noel Wilson", email = "jwnwilson@hotmail.co.uk"},
]
requires-python = "<4.0,>=3.12"
name = "hextech"
version = "0.1.0"
description = ""
readme = "README.md"
dependencies = [
    "pyyaml<7.0.0,>=6.0.2",
    "boto3<2.0.0,>=1.35.58",
    "pydantic-settings<3.0.0,>=2.6.1",
    "boto3-stubs[essential]<2.0.0,>=1.35.86",
    "hexrepo-cloud",
    "typer-slim>=0.15.1",
    "copier>=9.7.1",
]

[tool.uv.sources]
hexrepo-cloud = { path = "../../libs/adaptor/cloud", editable = true }

[project.scripts]
hextech = "hextech.interactor.cli:app"

[dependency-groups]
dev = [
    "pytest<9.0.0,>=8.3.4",
    "pytest-cookies<1.0.0,>=0.7.0",
    "mypy<2.0.0,>=1.13.0",
    "ruff>=0.8.4",
    "httpx<1.0.0,>=0.27.2",
    "pytest-dotenv<1.0.0,>=0.5.2",
    "pytest-cov<7.0.0,>=6.0.0",
    "pytest-xdist<4.0.0,>=3.6.1",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
