# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend Libs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Setting an environment variable with the value of a configuration variable
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MONOREPO_LIB_REPO_URL: ${{ vars.MONOREPO_LIB_REPO_URL }}
  MONOREPO_LIB_REPO_USERNAME: ${{ vars.MONOREPO_LIB_REPO_USERNAME }}
  MONOREPO_LIB_REPO_PASSWORD: ${{ secrets.MONOREPO_LIB_REPO_PASSWORD }}

permissions:
  contents: read

jobs:
  test_libs:
    strategy:
      matrix:
        library:
        - "backend/libs/src/adaptor/db"
        - "backend/libs/src/adaptor/storage"
        - "backend/libs/src/interactor/api"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Cache cli venv
      id: cache-cli-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-cli-poetry
      with:
        path: .venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles( 'poetry.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache lib venv
      id: cache-lib-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-lib-poetry
      with:
        path: "${{ matrix.library }}/.venv"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-${{ hashFiles( env.POETRY_LOCK_FILE ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-
    - name: Test Library
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make test_be_libs LIBRARY=${LIB}
  deploy_libs:
    strategy:
      matrix:
        library:
        - "backend/libs/src/adaptor/db"
        - "backend/libs/src/adaptor/storage"
        - "backend/libs/src/interactor/api"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - name: Cache cli venv
      id: cache-cli-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-cli-poetry
      with:
        path: .venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles( 'poetry.lock' ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache lib venv
      id: cache-lib-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-lib-poetry
      with:
        path: "${{ matrix.library }}/.venv"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-${{ hashFiles( env.POETRY_LOCK_FILE ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-
    - name: Deploy Library
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make deploy_be_libs LIBRARY=${LIB}
