# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_projects:
    strategy:
      matrix:
        project:
        - "backend/projects/example"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Cache cli venv
      id: cache-cli-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-cli-poetry
      with:
        path: ./.cli_venv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache project venv
      id: cache-project-poetry
      uses: actions/cache@v3
      env:
        cache-name: cache-project-poetry
      with:
        path: "${{ matrix.project }}/.venv"
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-${{ hashFiles( env.POETRY_LOCK_FILE ) }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.library }}-
    - name: Test Libraries
      run: make test_be_projects