# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Backend Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test_projects:
    strategy:
      matrix:
        project:
        - "backend/projects/example"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        venv_path: ${{ matrix.library }}
    - name: Test Libraries
      run: make test_be_projects