# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Libs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Setting an environment variable with the value of a configuration variable
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MONOREPO_LIB_REPO_URL: ${{ vars.MONOREPO_LIB_REPO_URL }}
  MONOREPO_LIB_REPO_USERNAME: ${{ vars.MONOREPO_LIB_REPO_USERNAME }}
  MONOREPO_LIB_REPO_PASSWORD: ${{ secrets.MONOREPO_LIB_REPO_PASSWORD }}

permissions:
  contents: read

jobs:
  test_libs:
    strategy:
      matrix:
        library:
        - "libs/src/adaptor/db"
        - "libs/src/adaptor/storage"
        - "libs/src/interactor/api"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        venv_path: ${{ matrix.library }}
        poetry_lock_file: "${{ matrix.library }}/poetry.lock"
    - name: Test Library
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make test_libs LIBRARY=${LIB}
  deploy_libs:
    needs: test_libs
    strategy:
      matrix:
        library:
        - "libs/src/adaptor/db"
        - "libs/src/adaptor/storage"
        - "libs/src/interactor/api"
    env:
      POETRY_LOCK_FILE: "${{ matrix.library }}/poetry.lock"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        venv_path: ${{ matrix.library }}
        poetry_lock_file: "${{ matrix.library }}/poetry.lock"
    - name: Deploy Library
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make deploy_libs LIBRARY=${LIB}
