# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Library Test & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - libs/**
  pull_request:
    branches: [ main ]
    paths:
      - libs/**

env:
  # Setting an environment variable with the value of a configuration variable
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  HEXREPO_LIB_REPO_URL: ${{ vars.HEXREPO_LIB_REPO_URL }}
  HEXREPO_LIB_REPO_USERNAME: ${{ vars.HEXREPO_LIB_REPO_USERNAME }}
  HEXREPO_LIB_REPO_PASSWORD: ${{ secrets.HEXREPO_LIB_REPO_PASSWORD }}

permissions:
  contents: read

jobs:
  test_libs:
    strategy:
      matrix:
        library:
        - "libs/adaptor/db"
        - "libs/adaptor/cloud"
        - "libs/interactor/api"
        - "libs/interactor/task"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_modified.outputs.skip }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.library }}/uv.lock"
    - name: Check Library Modified
      id: check_modified
      run: |
        set +e
        export LIB=`basename "${{ matrix.library }}"`
        make check_library_modified LIBRARY=${LIB}
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
        else
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Start LocalStack
      if: (matrix.library == 'libs/adaptor/db' || matrix.library == 'libs/interactor/task') && ${{ steps.check_modified.outputs.skip == 'false' }}
      uses: LocalStack/setup-localstack@v0.2.2
      with:
        image-tag: 'latest'
        install-awslocal: 'true'
    - name: Setup Test DBs
      if: matrix.library == 'libs/adaptor/db' && ${{ steps.check_modified.outputs.skip == 'false' }}
      working-directory: ${{ matrix.library }}
      run: |
        docker compose up postgres_db mongodb -d
    - name: Test Library
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      working-directory: ${{ matrix.library }}
      run: |
        make lint
        uv run pytest
  check_version_bump:
    strategy:
      matrix:
        library:
        - "libs/adaptor/db"
        - "libs/adaptor/cloud"
        - "libs/interactor/api"
        - "libs/interactor/task"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.library }}/uv.lock"
    - name: Check Version Bump Needed
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make check_library_bump LIBRARY=${LIB}
  deploy_libs:
    needs: test_libs
    strategy:
      fail-fast: false
      matrix:
        library:
        - "libs/adaptor/db"
        - "libs/adaptor/cloud"
        - "libs/interactor/api"
        - "libs/interactor/task"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_modified.outputs.skip }}
    if: github.ref == 'refs/heads/main' && needs.test_libs.result == 'success'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.library }}/uv.lock"
    - name: Check Library Modified
      id: check_modified
      run: |
        set +e
        export LIB=`basename "${{ matrix.library }}"`
        make check_library_modified LIBRARY=${LIB}
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
        else
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Deploy Library
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      run: |
        export LIB=`basename "${{ matrix.library }}"`
        make deploy_libs_check_modified LIBRARY=${LIB}
    
