# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Projects

on:
  push:
    branches: [ main ]
    paths:
      - libs/**
      - projects/**
  pull_request:
    branches: [ main ]
    paths:
      - libs/**
      - projects/**

permissions:
  contents: read

jobs:
  test_projects:
    strategy:
      matrix:
        project:
        - "projects/example"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        venv_path: ${{ matrix.project }}
        poetry_lock_file: "${{ matrix.project }}/poetry.lock"
    - name: Test Libraries
      run: make test_projects
  plan_infra:
    needs: test_projects
    strategy:
      matrix:
        project:
        - "projects/example"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Infra
      run: |
        cd ${{ matrix.project }}
        make tf_init
        make tf_plan
  deploy_projects:
    environment: production
    needs: test_infra
    strategy:
      matrix:
        project:
        - "projects/example"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        venv_path: ${{ matrix.project }}
        poetry_lock_file: "${{ matrix.project }}/poetry.lock"
    - name: Update Infra
      run: |
        cd ${{ matrix.project }}
        make tf_init
        make tf_apply
    - name: Deploy Project
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make deploy_projects PROJECT=${PROJ}