# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Projects Test & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - libs/**
      - projects/**
  pull_request:
    branches: [ main ]
    paths:
      - libs/**
      - projects/**

env:
  # Setting an environment variable with the value of a configuration variable
  TF_VAR_AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  TF_VAR_AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  test_projects:
    strategy:
      matrix:
        project:
        - "projects/example"
        - "projects/monitor"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_modified.outputs.skip }}
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.project }}/uv.lock"
    - name: Check Project Modified
      id: check_modified
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make check_project_modified PROJECT=${PROJ}
        retVal=$?
        echo "retVal: $retVal"
        if [ $retVal -ne 0 ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
        else
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Start Test DB
      if: matrix.project == 'projects/example' && steps.check_modified.outputs.skip == 'false'
      working-directory: ${{ matrix.project }}
      run: |
        echo ${{ steps.check_modified.outputs.skip }}
        make db
    - name: Test Projects
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      working-directory: ${{ matrix.project }}
      run: |
        make lint
        make test
  plan_infra:
    needs: test_projects
    strategy:
      matrix:
        project:
        - "projects/example"
        - "projects/monitor"
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_modified.outputs.skip }}
    steps:
    - uses: actions/checkout@v4
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.project }}/uv.lock"
    - name: Check Project Modified
      id: check_modified
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make check_project_modified PROJECT=${PROJ}
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
        else
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false
    - name: Infra plan
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      working-directory: ${{ matrix.project }}
      run: |
        make tf_init
        make tf_plan
  deploy_projects:
    environment: production
    needs: plan_infra
    outputs:
      skip: ${{ steps.check_modified.outputs.skip }}
    if: github.ref == 'refs/heads/main' && needs.plan_infra.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        project:
          - "projects/example"
          - "projects/monitor"
        env:
          - "default"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
    - id: python_venv
      name: Cache project venv
      uses: ./.github/actions/be_venv
      with:
        lock_file: "${{ matrix.project }}/uv.lock"
    - name: Check Project Modified
      id: check_modified
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make check_project_modified PROJECT=${PROJ}
        retVal=$?
        if [ $retVal -ne 0 ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
        else
            echo "skip=true" >> $GITHUB_OUTPUT
        fi
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false
    - name: DB migration
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      shell: bash
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make migrate_db PROJECT=${PROJ} ENV=${{ matrix.env }} 
    - name: Deploy Project
      if: ${{ steps.check_modified.outputs.skip == 'false' }}
      shell: bash
      run: |
        export PROJ=`basename "${{ matrix.project }}"`
        make deploy_projects_check_modified PROJECT=${PROJ} ENV=${{ matrix.env }}
